version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "loanstreet-interview"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6l0rrz4ckhrx"
s3_prefix = "loanstreet-interview"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

